<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <?php echo ($this->getChild('head')->toHtml())?>
</head>
<body>
    

    <div class=""><pre><?php echo ($this->getChildHtml('header'))?></div>
    <div class=""><pre><?php echo ($this->getChildHtml('footer'))?></div>
    <div class=""><pre><?php echo ($this->getChildHtml('content'))?></div>
    <div class=""><pre><?php echo ($this->getChildHtml('massages'))?></div>


</body>
</html>