<header class="header">
    <a href="https://jinil09.github.io/MyPortfolio/" class="logo"><img src="<?php echo Mage::getBaseUrl('skin/img/logo.png')?>" alt="Hello"></a>

    <nav class="navbar">
        <ul>
            <li><a href="http://localhost/Practice/mvc_project/page/index/index">Home</a></li>
            <li><a href="http://localhost/Practice/mvc_project/admin/catalog_product/form">Product Form</a></li>
            <li><a href="http://localhost/Practice/mvc_project/admin/catalog_product/list">Product List</a></li>
            <li><a href="http://localhost/Practice/mvc_project/admin/catalog_category/form">Category Form</a></li>
            <li><a href="http://localhost/Practice/mvc_project/admin/catalog_category/list">Category List</a></li>
        </ul>
    </nav>
</header>