<?php $this->logInOutText()?>
<header class="header">
    <a href="https://jinil09.github.io/MyPortfolio/" class="logo"><img src="<?php echo Mage::getBaseUrl('skin/img/logo.png')?>" alt="Hello"></a>

    <nav class="navbar">
        <ul>
            <li><a href="<?php echo Mage::getBaseUrl('page/index/index') ?>">Home</a></li>
            <li><a href="<?php echo Mage::getBaseUrl('customer/account/dashboard') ?>">DashBoard</a></li>
            <li><a href="<?php echo Mage::getBaseUrl('admin') ?>">Admin Panel</a></li>
            <li><a href="<?php echo $this->link;?>" class="login-button"><?php  echo $this->logInOutText(); ?></a></li>
        </ul>
    </nav>
</header>
