<?php
$userData = $this->getUserData();
?>



<section class="list">
    <h2>History</h2>

    <table border="1">
        <tr>
            <th>Id</th>
            <th>User Name</th>
            <th>Country</th>
            <th>Currency Country</th>
            <th>Amount</th>
            <th>Result</th>
        </tr>
        <?php foreach ($userData->getData() as $user): ?>
            <tr>
                <td>
                    <?= $user->getId() ?>
                </td>
                <td>
                    <?= $user->getUserName() ?>
                </td>
                <td>
                    <?=  $this->getCountryIdByName($user->getCountry())  ?>
                </td>
                <td>
                    <?= $this->getCountryIdByName($user->getCurrencyCountry())  ?>
                </td>
                <td>
                    <?= $user->getAmount() ?>
                </td>
                <td>
                    <?= $user->getResult() ?>
                </td>

            </tr>
        <?php endforeach; ?>
    </table>
</section>
