<?php   $listModel =  Mage::getModel('catalog/product')->loadAllData() ;?>

<section class="list">
<h2>Product List</h2>
    <table border="1">
        <tr>
            <th>Product Id</th>
            <th>Product Name</th>
            <th>SKU</th>
            <th>Category</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php foreach ($listModel as $product): ?>
            <tr>
                <td style="width:30px"><?= $product['product_id'] ?></td>
                <td><?= $product['name'] ?></td>
                <td><?= $product['sku'] ?></td>
                <td><?= $product['category_id'] ?></td>
                <td><a href="http://localhost/Practice/mvc_project/admin/catalog_product/form?edit=<?= $product['product_id'] ?>">Edit</a></td>
                <td><a href="http://localhost/Practice/mvc_project/admin/catalog_product/delete?id=<?= $product['product_id'] ?>">Delete</a></td>
            </tr>
        <?php endforeach; ?>
  </table>
</section>




