<?php $bannerData = $this->getBannerData();
?>

<div class="slideshow-container">
    <?php foreach ($bannerData->getData() as $banner): ?>
        <div class="mySlides fade">
            <!-- <div class="numbertext">1 / 3</div> -->
            <img src="<?php echo Mage::getBaseUrl('media/banner/' . $banner->getBannerImage()) ?>" style="width:100%">
            <div class="text">Caption Text</div>
        </div>
    <?php endforeach; ?>
</div>


<script>

    let slideIndex = 0;
    showSlides();

    function showSlides() {
        let i;
        let slides = document.getElementsByClassName("mySlides");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) { slideIndex = 1 }
        slides[slideIndex - 1].style.display = "block";
        setTimeout(showSlides, 6000); // Change image every 2 seconds
    }
</script>